name: Index the registry

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

concurrency: indexing_stage

jobs:
  registryindex:
    name: "Index the Julia General registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      - run: julia -e 'using Pkg; Pkg.develop("SymbolServer")'
      - run: julia ~/.julia/dev/SymbolServer/registryindexer/main.jl $GITHUB_WORKSPACE/store 2
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
